# Generated by Django 2.1.15 on 2020-09-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0008_metadata_archive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsumptionMobile',
        ),
        migrations.DeleteModel(
            name='DegreeDay',
        ),
        migrations.DeleteModel(
            name='MetaData',
        ),
        migrations.DeleteModel(
            name='Remark',
        ),
        migrations.AddField(
            model_name='metadata_main',
            name='reminder_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata_main',
            name='reminder_week1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
