# Generated by Django 2.1.15 on 2020-09-30 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0009_auto_20200929_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata_main',
            old_name='reminder_week1',
            new_name='reminder_week',
        ),
    ]
