# Generated by Django 2.1.15 on 2020-09-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0010_auto_20200929_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata_main',
            name='reminder_flag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
