# Generated by Django 2.1.15 on 2020-10-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0011_metadata_main_reminder_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata_activity',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='metadata_main',
            name='contacts',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
