# Generated by Django 2.1.15 on 2020-10-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0012_auto_20201001_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='technical_authority',
            field=models.CharField(max_length=1000),
        ),
    ]
